version: "3.8"
services:
  db:
    build:
      context: ./database
      dockerfile: docker/Dockerfile
    restart: 'always'
    volumes:
    - ./database/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - "3306:3306"

  api:
    build:
      context: ./api
      dockerfile: docker/Dockerfile
    volumes:
      - ./api:/api
    depends_on:
      - db
    ports:
    - "81:81"
